apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.app }}
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}